# Generated by Django 4.2.13 on 2024-07-03 15:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='Город')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Адрес склада')),
                ('description', models.TextField(verbose_name='Описание')),
                ('road', models.TextField(verbose_name='описание проезда')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный телефон')),
                ('temperature', models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)], verbose_name='Температура на складе')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorehouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pic', models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Номер картинки')),
                ('img', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('storehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storage.storehouse', verbose_name='Склад')),
            ],
            options={
                'ordering': ['number_pic'],
            },
        ),
        migrations.CreateModel(
            name='Requestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Почта пользователя')),
                ('created_at', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('expiration_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата окончания аренды')),
                ('price', models.PositiveSmallIntegerField(help_text='высчитывается после обработки заявки', null=True, verbose_name='стоимость хранения за год')),
                ('status', models.CharField(choices=[('SD', 'Send'), ('VD', 'Viewed'), ('CD', 'Contacted'), ('PD', 'Paid'), ('DD', 'Delivered'), ('FD', 'Finished')], default='SD', max_length=2, verbose_name='статус заявки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='storage.userprofile', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='номер бокса')),
                ('floor', models.CharField(max_length=3, verbose_name='Этаж')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='длина')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ширина')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='высота')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('requestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='storage.requestion', verbose_name='Заявка на аренду')),
                ('storehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.storehouse', verbose_name='Склад')),
            ],
        ),
    ]
