# Generated by Django 4.2.13 on 2024-06-30 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Requestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('expiration_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата окончания аренды')),
                ('price', models.PositiveSmallIntegerField(help_text='высчитывается после обработки заявки', null=True, verbose_name='стоимость хранения за год')),
                ('status', models.CharField(choices=[('SD', 'Send'), ('VD', 'Viewed'), ('CD', 'Contacted'), ('PD', 'Paid'), ('DD', 'Delivered'), ('FD', 'Finished')], default='SD', max_length=2, verbose_name='статус заявки')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='storage.box', verbose_name='Бокс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='storage.userprofile', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
