# Generated by Django 4.2.13 on 2024-06-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_userprofile_phone_number_storehouseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email пользователя')),
                ('price', models.PositiveSmallIntegerField(help_text='высчитывается после обработки заявки', null=True, verbose_name='стоимость хранения за год')),
                ('status', models.CharField(choices=[('SD', 'Send'), ('VD', 'Viewed'), ('CD', 'Contacted'), ('PD', 'Paid'), ('DD', 'Delivered'), ('FD', 'Finished')], default='SD', max_length=2, verbose_name='статус заявки')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='requestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='storage.requestion', verbose_name='заяка на аренду бокса'),
        ),
    ]
